// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVIM9tpmAuzwnIFr4phJK40ZsGhjwmxQE',
    appId: '1:933161310912:web:75cb22a94a403ede4beb25',
    messagingSenderId: '933161310912',
    projectId: 'gammal-tech-community-aca17',
    authDomain: 'gammal-tech-community-aca17.firebaseapp.com',
    storageBucket: 'gammal-tech-community-aca17.appspot.com',
    measurementId: 'G-E9QLNVC7FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_SoWi9IlBP617DTYEg8jbOUgpfaL7szc',
    appId: '1:933161310912:android:95106f0ed02ea4e34beb25',
    messagingSenderId: '933161310912',
    projectId: 'gammal-tech-community-aca17',
    storageBucket: 'gammal-tech-community-aca17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSM0Z3cSRV05YSNCZiVphLNC8RwOsCF14',
    appId: '1:933161310912:ios:590de21cccb9ed944beb25',
    messagingSenderId: '933161310912',
    projectId: 'gammal-tech-community-aca17',
    storageBucket: 'gammal-tech-community-aca17.appspot.com',
    androidClientId: '933161310912-ipu4s1hicrr23m2ujeilhv8u1jrq131t.apps.googleusercontent.com',
    iosClientId: '933161310912-8ehodk9q773hqg0b89op3r7m6os7qtn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gammalTechCommunity',
  );
}
